---
version: 0.2.1
slug: octodns-gui
name: OctoDNS GUI
description: Web-basierte GUI zur Verwaltung von DNS-Zonen mit OctoDNS
url: https://github.com/helix-git/haos-octodns-gui
arch:
  - aarch64
  - amd64
image: ghcr.io/helix-git/haos-octodns-gui/{arch}
init: false
ingress: true
ingress_port: 8100
ingress_entry: /
auth_api: true
homeassistant_config: true
map:
  - config:rw
options:
  enabled_providers:
    - netbox-dns
    - pihole
  zone_file_path: /config/octodns
schema:
  enabled_providers:
    - list(cloudflare|ovh|pihole|netbox-dns|netbox|bind)?
  zone_file_path: str
