---
version: 0.3.0
slug: octodns-gui
name: OctoDNS GUI
description: Web-basierte GUI zur Verwaltung von DNS-Zonen mit OctoDNS
url: https://github.com/helix-git/haos-octodns-gui
arch:
  - aarch64
  - amd64
image: ghcr.io/helix-git/haos-octodns-gui/{arch}
init: false
ingress: true
ingress_port: 8100
ingress_entry: /
auth_api: true
homeassistant_config: true
map:
  - config:rw
options:
  providers:
    cloudflare: false
    ovh: false
    pihole: true
    netbox_dns: true
    netbox: false
    bind: false
  zone_file_path: /config/octodns
schema:
  providers:
    cloudflare: bool?
    ovh: bool?
    pihole: bool?
    netbox_dns: bool?
    netbox: bool?
    bind: bool?
  zone_file_path: str
